### ISSUE TITLE
Wrong UMM manager Number

### ISSUE THREAD

**Issue by Littlebob86** [thehambeard/WIT#10]
Hey Ham, 

You've got UMM version 0.23.5, but it should be 0.23.4 :)

**Comment by thehambeard** [comment]
No it shouldn't, I am using 0.23.5, I am sure 23.4 is fine though.

**Comment by eyalhaim1** [comment]
https://www.nexusmods.com/site/mods/21?tab=description
![image](https://user-images.githubusercontent.com/91762509/143690953-bc11a65d-d51d-4004-bad4-8db36eb12642.png)
