### ISSUE TITLE
Not working for my MC

### ISSUE THREAD

**Issue by The-Talik** [thehambeard/WIT#27]
For some reason on my MC (Oracle) this mod gives me "No spells to cast".  Works perfectly fine on all of my other casters.  Anything I can do to get it working?

**Comment by thehambeard** [comment]
Do you have a mod list and a save I can test?

**Comment by The-Talik** [comment]
Thanks!
Mods:
TTT Base
TTT Core
Toybox
Respec
Weapon Focus Plus
Bubble Buffs
Bubble Tweaks
CraftMaster
Finnean Tweaks
Respec Mod
And this mod
[Manual_78_Gray_Garrison__2_Rova__IX__4715__14_39_13.zip](https://github.com/user-attachments/files/16103870/Manual_78_Gray_Garrison__2_Rova__IX__4715__14_39_13.zip)

**Comment by thehambeard** [comment]
Should be fixed. Download new version.

**Comment by The-Talik** [comment]
Thanks!  Working great!
